main/urls.py
from django.urls import path

from main.views import (
    create_product,
    create_product_ajax,
    login_user,
    logout_user,
    register,
    show_json,
    show_json_by_id,
    show_main,
    show_xml,
    show_xml_by_id,
)

app_name = "main"  # pylint: disable=invalid-name
urlpatterns = [
    path("", show_main, name="show_main"),
    path("create-product", create_product, name="create_product"),
    path("xml", show_xml, name="show_xml"),
    path("json", show_json, name="show_json"),
    path("xml/<int:id>", show_xml_by_id, name="show_xml_by_id"),
    path("json/<int:id>", show_json_by_id, name="show_json_by_id"),
    path("register", register, name="register"),
    path("login", login_user, name="login"),
    path("logout", logout_user, name="logout"),
    path("create-product-ajax", create_product_ajax, name="create_product_ajax"),
]

shopping_list/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("main.urls")),
]

main/models.py
from django.contrib.auth.models import User
from django.db import models


class Product(models.Model):
    name = models.CharField(max_length=255)
    date_added = models.DateField(auto_now_add=True)
    price = models.IntegerField()
    description = models.TextField()
    user = models.ForeignKey(User, on_delete=models.CASCADE)

main/forms.py
from django.forms import ModelForm

from main.models import Product


# pylint: disable=too-few-public-methods
class ProductForm(ModelForm):
    class Meta:
        model = Product
        fields = ["name", "price", "description"]

main/views.py
from http import HTTPStatus

from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.core import serializers
from django.core.exceptions import ObjectDoesNotExist
from django.http import (
    HttpRequest,
    HttpResponse,
    HttpResponseNotFound,
    HttpResponseRedirect,
)
from django.shortcuts import redirect, render
from django.urls import reverse
from django.views.decorators.csrf import csrf_exempt

from main.forms import ProductForm
from main.models import Product


@login_required(login_url="/login")
def show_main(request: HttpRequest) -> HttpResponse:
    products = Product.objects.filter(user=request.user)

    context: dict = {
        "name": request.user.username,
        "class": "PBP Int.",
        "products": products,
        # This conditional is not required if @login_required works properly
        # Nevertheless, it is still a good practice to check for any input coming from user
        # Even though not explicitly stated, cookie is a part of input transmitted from user/cient!
        "last_login": request.COOKIES["last_login"]
        if "last_login" in request.COOKIES.keys()
        else "",
    }

    return render(request, "main.html", context)


@login_required(login_url="/login")
def create_product(request: HttpRequest) -> HttpResponse:
    form = ProductForm(request.POST or None)

    if form.is_valid() and request.method == "POST":
        product: Product = form.save(commit=False)
        product.user = request.user
        product.save()
        return HttpResponseRedirect(reverse("main:show_main"))

    context: dict = {
        "form": form,
    }

    return render(request, "create_product.html", context)


def show_xml(request: HttpRequest) -> HttpResponse:
    products = Product.objects.all()

    return HttpResponse(
        serializers.serialize("xml", products), content_type="application/xml"
    )


def show_json(request: HttpRequest) -> HttpResponse:
    products = Product.objects.all()

    return HttpResponse(
        serializers.serialize("json", products), content_type="application/json"
    )


def show_xml_by_id(request: HttpRequest, id: int) -> HttpResponse:
    # See: https://docs.djangoproject.com/en/4.2/topics/db/queries/#retrieving-a-single-object-with-get
    try:
        product = Product.objects.get(pk=id)
        return HttpResponse(
            serializers.serialize("xml", [product]), content_type="application/xml"
        )
    except ObjectDoesNotExist as product_not_found:
        return HttpResponseRedirect(reverse("main:show_xml"))


def show_json_by_id(request: HttpRequest, id: int) -> HttpResponse:
    # See: https://docs.djangoproject.com/en/4.2/topics/db/queries/#retrieving-a-single-object-with-get
    try:
        product = Product.objects.get(pk=id)
        return HttpResponse(
            serializers.serialize("json", [product]), content_type="application/json"
        )
    except ObjectDoesNotExist as product_not_found:
        return HttpResponseRedirect(reverse("main:show_json"))


def register(request: HttpRequest) -> HttpResponse:
    form: UserCreationForm = UserCreationForm()

    if request.method == "POST":
        form = UserCreationForm(request.POST)

        if form.is_valid():
            form.save()
            messages.success(request, "Your account has been successfully created!")

    context: dict = {
        "form": form,
    }

    return render(request, "register.html", context)


def login_user(request: HttpRequest) -> HttpResponse:
    if request.method == "POST":
        username: str = request.POST.get("username")
        password: str = request.POST.get("password")
        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            response: HttpResponse = redirect("main:show_main")
            response.set_cookie("last_login", str(datetime.datetime.now()))
            return response
        else:
            messages.info(
                request, "Sorry, incorrect username or password. Please try again."
            )

    context: dict = {}

    return render(request, "login.html", context)


def logout_user(request: HttpRequest) -> HttpResponse:
    logout(request)
    response: HttpResponse = redirect("main:login")
    response.delete_cookie("last_login")
    return response


@csrf_exempt
def create_product_ajax(request: HttpRequest) -> HttpResponse:
    form = ProductForm(request.POST)

    if form.is_valid() and request.method == "POST":
        product: Product = form.save(commit=False)
        product.user = request.user
        product.save()

        return show_json_by_id(request, id=product.pk)

    return HttpResponseNotFound()

main/templates/create_product.html
{% extends "base.html" %}

{% block content %}
<h1>Add New Product</h1>

<form method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Add Product" />
            </td>
        </tr>
    </table>
</form>
{% endblock %}

main/templates/edit_product.html
{% extends "base.html" %}

{% load static %}

{% block content %}

<h1>Edit Product</h1>

<form method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
        <tr>
            <td></td>
            <td>
                <input type="submit" value="Edit Product" />
            </td>
        </tr>
    </table>
</form>

{% endblock %}

main/templates/login.html
{% extends "base.html" %}

{% block meta %}
<title>Login</title>
{% endblock meta %}

{% block content %}
<div class="login">
    <h1>Login</h1>
    <form method="post" action="">
        {% csrf_token %}
        <table>
            <tr>
                <td>Username: </td>
                <td>
                    <input type="text" name="username" placeholder="Username" class="form-control" />
                </td>
            </tr>
            <tr>
                <td>Password: </td>
                <td>
                    <input type="password" name="password" placeholder="Password" class="form-control" />
                </td>
            </tr>
            <tr>
                <td></td>
                <td>
                    <input class="btn login_btn" type="submit" value="Login" />
                </td>
            </tr>
        </table>
    </form>

    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}

    <p>
        Don't have an account yet? <a href="{% url 'main:register' %}">Register now</a>
    </p>
</div>
{% endblock content %}

main/templates/main.html
{% extends "base.html" %}

{% load static %}

{% block meta %}
<title>Shopping List</title>
{% endblock meta %}

{% block content %}
<h1>Shopping List Page</h1>
<h5>Name:</h5>
<p>{{ name }}</p>
<h5>Class:</h5>
<p>{{ class }}</p>
<table>
    <tr>
        <th>Name</th>
        <th>Price</th>
        <th>Description</th>
        <th>Date Added</th>
        <th colspan="2">Actions</th>
    </tr>
    {% comment %} Some comments ... {% endcomment %}
    {% for product in products %}
    <tr>
        <td>{{ product.name }}</td>
        <td>{{ product.price }}</td>
        <td>{{ product.description }}</td>
        <td>{{ product.date_added }}</td>
        <td>
            <a href="{% url 'main:edit_product' product.pk %}">
                <button>
                    Edit
                </button>
            </a>
        </td>
        <td>
            <a href="{% url 'main:delete_product' product.pk %}">
                <button>
                    Delete
                </button>
            </a>
        </td>
    </tr>
    {% endfor %}
</table>

<br />

<a href="{% url 'main:create_product' %}">
    <button>
        Add New Product
    </button>
</a>

<a href="{% url 'main:logout' %}">
    <button>
        Logout
    </button>
</a>

<h5>Last login session: {{ last_login }}</h5>

{% endblock content %}

main/templates/register.html
{% extends "base.html" %}

{% block meta %}
<title>Register</title>
{% endblock meta %}

{% block content %}
<div class="login">
    <h1>Register</h1>
    <form method="post">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
            <tr>
                <td></td>
                <td>
                    <input type="submit" name="submit" value="Register" />
                </td>
            </tr>
        </table>
    </form>
    {% if messages %}
    <ul>
        {% for message in messages %}
        <li>{{ message }}</li>
        {% endfor %}
    </ul>
    {% endif %}
</div>
{% endblock content %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    {% block meta %}
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% endblock meta %}
    <!--
        Follow Bootstrap usage via CDN (Content Delivery Network) as documented at: 
        https://getbootstrap.com/docs/5.3/getting-started/download/#cdn-via-jsdelivr
    -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.8/dist/umd/popper.min.js"
        integrity="sha384-I7E8VVD/ismYTF4hNIPjVp/Zjvgyol6VFvRkX/vR+Vc4jQkC+hVqc2pM8ODewa9r"
        crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.min.js"
        integrity="sha384-BBtl+eGJRgqQAUMxJ7pMwbEyER4l1g+O15P+16Ep7Q9Q+zqX6gSbd85u4mG4QzX+"
        crossorigin="anonymous"></script>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous" />
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL"
        crossorigin="anonymous"></script>
    <!-- Use jQuery provided via their official CDN -->
    <script src="https://code.jquery.com/jquery-3.7.1.slim.min.js"
        integrity="sha256-kmHvs0B+OpCW5GVHUNjv9rOmY0IvSIRcf7zGUDTDQM8=" crossorigin="anonymous"></script>
    <!-- App-specific CSS and JS -->
    <link rel="stylesheet" href="{% static 'main/tutorial.css' %}" />
</head>

<body>
    {% block content %}
    {% endblock content %}
</body>

</html>